### ISSUE TITLE
Misconceptions about silex/emacs

### ISSUE THREAD

**Issue by Silex** [jgkamat/airy-docker-emacs#4]
Hello,

Your readme spreads a bit of FUD about my repository so I thought I'd set the record straight :wink: 

> 1. It’s huge, weighing in at almost 900mb.

The alpine images are ~200MB, the main images are ~500MB and the dev images are around 1400MB.

> 2. It contains all of Emacs build dependencies, which are generally unneeded at run time.

Not in the main/alpine images.

> 3. It is self-compiled, which can lead to missing features (making sure everything is properly compiled is a pain)

Nothing to say here :grin: 

> 4. Suffers from https://github.com/moby/moby/issues/22801

I don't quite understand this point. All emacs images suffer from this when you try to build them inside a Dockerfile (well, not anymore in the next versions since the portable dumper branch was merged).

> 5. It is not an automated build (leading to trust issues).

It is automated since more or less forever, see https://travis-ci.org/Silex/docker-emacs.

**Comment by jgkamat** [comment]
Philippe Vaucher writes:

>> 1. It’s huge, weighing in at almost 900mb.
>
> The alpine images are ~200MB, the main images are ~500MB and the dev images 
> are around 1400MB.

Sure, I'll update this with these statistics I just pulled.

jgkamat/emacs       25.2                4f0690971728        5 minutes ago 
125MB
silex/emacs         25.2                aaceed10ec61        8 days ago 
455MB
silex/emacs         25.2-dev            584386f1f7b2        8 days ago 
1.37GB
silex/emacs         25.2-alpine         f174f50d261e        2 months ago 
223MB
silex/emacs         25.2-alpine-dev     2ddbf35762d6        2 months ago 
1.16GB

>> 2. It contains all of Emacs build dependencies, which are generally 
>> unneeded at run time.
>
> Not in the main/alpine images.

Updated with a note. I don't understand this though, where are you removing 
the dependencies?

http://www.github.com/silex/docker-emacs/blob/master/25.2/alpine/3.9/Dockerfile

>> 4. Suffers from https://github.com/moby/moby/issues/22801
>
> I don't quite understand this point. All emacs images suffer from this.

This one does not - since there is no compilation we don't suffer from that 
issue. I can build these images on my laptop, but silex/emacs fails to build 
(last I checked).

>> 5. It is not an automated build (leading to trust issues).
>
> It is automated since more or less forever, see 
> https://travis-ci.org/Silex/docker-emacs.

silex/emacs is still not an automated build in docker terminology (which is 
renamed to "autobuild" now). There is no assurance that the images built by 
travis are the ones pushed. In this setup, you need to trust travis, you, and 
the dockerhub.

This image is build by the docker-hub, all I do is provide the dockerfiles. 
So, assuming you audit the dockerfiles (and alpine packaging in this case), 
you only need to trust the dockerhub.

See http://www.praqma.com/stories/trust-in-docker-images/ for an overview of 
the idea.

**Comment by Silex** [comment]
>> 2. It contains all of Emacs build dependencies, which are generally > unneeded at run time. Not in the main/alpine images.

> Updated with a note. I don't understand this though, where are you removing the dependencies?

https://github.com/silex/docker-emacs/blob/master/25.2/alpine/3.9/Dockerfile#L58-L84

It's a multistage build. The first part of the dockerfile is the `dev` image, with the build dependencies. The second part are just the runtime dependencies needed for emacs to run, and the emacs binary copied from the dev image.

>> 4. Suffers from [moby/moby#22801](https://github.com/moby/moby/issues/22801) I don't quite understand this point. All emacs images suffer from this.

> This one does not - since there is no compilation we don't suffer from that issue. I can build these images on my laptop, but silex/emacs fails to build (last I checked).

Ah, right I understand what you mean now.

>> 5. It is not an automated build (leading to trust issues). It is automated since more or less forever, see https://travis-ci.org/Silex/docker-emacs.

> silex/emacs is still not an automated build in docker terminology (which is renamed to "autobuild" now). There is no assurance that the images built by travis are the ones pushed. In this setup, you need to trust travis, you, and the dockerhub. This image is build by the docker-hub, all I do is provide the dockerfiles. So, assuming you audit the dockerfiles (and alpine packaging in this case), you only need to trust the dockerhub. See http://www.praqma.com/stories/trust-in-docker-images/ for an overview of the idea.

Yeah ok it's a logical consequence of the previous point.

Thanks for clarifying :+1:

**Comment by Silex** [comment]
> 2. Most images (non-alpine) contain all of Emacs build dependencies, which are generally unneeded at run time.

To be really precise only half the images contain all of the Emacs build dependencies:

This project provides different docker images:

- The main images (~500MB) only contain the runtime dependencies for Emacs to run.
- The `-dev` variants (~1400MB) contain additional developer tools such as [Cask](https://cask.readthedocs.io),
  [git](https://git-scm.com) and [Python](https://www.python.org). The Emacs source is available at `/opt/emacs` if
  you need to build Emacs differently.
- The `-alpine` variants (~200MB) follow the same logic as the main images but are based on
  [Alpine Linux](https://alpinelinux.org).

So, for each version you have:

- `26.3` no build deps (ubuntu).
- `26.3-alpine` no build deps (alpine).
- `26.3-dev` with build deps (ubuntu).
- `26.3-alpine-dev` with build deps (alpine).

**Comment by jgkamat** [comment]
Philippe Vaucher writes:

> - `26.3` no build deps (ubuntu).
> - `26.3-alpine` no build deps (alpine).
> - `26.3-dev` with build deps (ubuntu).
> - `26.3-alpine-dev` with build deps (alpine).


Ah, I see, I'll modify that point to just say the dev images have build deps. 
This is relevant because I need cask to run my CI
